version: '3.8'

# 컨테이너
services:

  # 컨테이너 명
  db:
    image: postgres:11
    container_name: database-server
    environment: # 환경설정
      POSTGRES_USER: cmeapp
      POSTGRES_PASSWORD: cmepwd
      POSTGRES_DB: cmedb
    ports:
      - "9966:9966"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - database-network


networks:
  database-network:

volumes:
  pgdata: