version: '3.8'

# 컨테이너
services:

  # 컨테이너 명
  db:
    image: postgres:11
    container_name: database-server
    environment: # 환경설정
      POSTGRES_USER: cmeapp
      POSTGRES_PASSWORD: cmepwd
      POSTGRES_DB: cmedb
    ports:
      - "5432:5432" # 포트 수정: 호스트 포트와 컨테이너 포트를 맞춰준다.
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network # 백엔드 서비스와 동일한 네트워크에 속하도록 설정한다.


networks:
  backend-network: # 백엔드 서비스와 동일한 네트워크를 정의한다.

volumes:
  pgdata: